services:
  - type: web
    name: googlebooks-app-server
    env: node
    buildCommand: npm run build-server
    startCommand: npm run start-server
    envVars:
      - key: NODE_ENV
        value: production
    regions:
      - global

  - type: static-site
    name: googlebooks-app-client
    buildCommand: npm run build-client
    staticPublishPath: ./client/build
    envVars:
      - key: NODE_ENV
        value: production
    regions:
      - global

databases:
  # Example if you need a database
  - type: postgres
    name: googlebooks-db
    version: 12
    region: global
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: googlebooks-db
          property: connectionString